import { Question, TopicDataMap } from "../types/quiz.types";

export const QUIZ_DURATION = 15 * 60;

export const mockQuestions: Question[] = [
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "geography",
    yearAsked: 2023,
    questionText: "What is the capital of France?",
    optionA: "Paris",
    optionB: "London",
    optionC: "Berlin",
    optionD: "Madrid",
    correctAnswer: "A",
    solution: "Paris is the capital of France.",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "science",
    yearAsked: 2023,
    questionText: "Which planet is known as the Red Planet?",
    optionA: "Venus",
    optionB: "Mars",
    optionC: "Jupiter",
    optionD: "Saturn",
    correctAnswer: "B",
    solution: "Mars is known as the Red Planet.",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "math",
    yearAsked: 2023,
    questionText: "What is $2 + 2$?",
    optionA: "$3$",
    optionB: "$4$",
    optionC: "$5$",
    optionD: "$6$",
    correctAnswer: "B",
    solution: "$2 + 2$ equals $4$.",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "literature",
    yearAsked: 2023,
    questionText: "Who wrote 'To Kill a Mockingbird'?",
    optionA: "Harper Lee",
    optionB: "J.K. Rowling",
    optionC: "Stephen King",
    optionD: "Mark Twain",
    correctAnswer: "A",
    solution: "Harper Lee wrote 'To Kill a Mockingbird'.",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "math",
    yearAsked: 2023,
    questionText: "Solve: $x^2 - 5x + 6 = 0$",
    optionA: "$x = 2, 3$",
    optionB: "$x = -2, -3$",
    optionC: "$x = 1, 6$",
    optionD: "$x = -1, -6$",
    correctAnswer: "A",
    solution: "$(x - 2)(x - 3) = 0$ $\\Rightarrow x = 2, 3$",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "science",
    yearAsked: 2023,
    questionText: "Which element has the chemical symbol '$O$'?",
    optionA: "Oxygen",
    optionB: "Gold",
    optionC: "Silver",
    optionD: "Iron",
    correctAnswer: "A",
    solution: "Oxygen is '$O$'.",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "math",
    yearAsked: 2025,
    questionText: "What is the square root of $16$?",
    optionA: "$2$",
    optionB: "$3$",
    optionC: "$4$",
    optionD: "$5$",
    correctAnswer: "C",
    solution: "$\\sqrt{16} = 4$",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "math",
    yearAsked: 2026,
    questionText: "Solve: $2x^2 - 7x + 3 = 0$",
    optionA: "$x = 3, 1/2$",
    optionB: "$x = -3, -1/2$",
    optionC: "$x = 1, 3$",
    optionD: "$x = 2, 3/2$",
    correctAnswer: "A",
    solution: "$x = 3$ or $x = \\frac{1}{2}$",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "science",
    yearAsked: 2023,
    questionText: "What is the hardest natural substance?",
    optionA: "Gold",
    optionB: "Iron",
    optionC: "Diamond",
    optionD: "Quartz",
    correctAnswer: "C",
    solution: "Diamond is the hardest.",
  },
  {
    examId: "mock-exam-1",
    topicId: "general",
    subtopicId: "science",
    yearAsked: 2023,
    questionText: "Which gas do plants absorb?",
    optionA: "Oxygen",
    optionB: "Nitrogen",
    optionC: "Carbon Dioxide",
    optionD: "Hydrogen",
    correctAnswer: "C",
    solution: "Plants absorb Carbon Dioxide.",
  },
];

